### PR TITLE
Fixed dead link on ios readme

### PR DESCRIPTION
**Pull request by SamirMokiem**
Forgot a # on the link

### CODE REVIEW

**Comment by simonzhexu** [comment]
@SamirMokiem thanks for contributing. Please follow the contribution guide https://github.com/WhatsApp/stickers/blob/master/CONTRIBUTING.md to sign CLA

**Comment by SamirMokiem** [comment]
Fork the repo and create your branch from master.
✔
If you've added code that should be tested, add tests.
No code. Just 1 character
If you've changed APIs, update the documentation.
Ensure the test suite passes.
ake sure your code lints.
If you haven't already, complete the Contributor License Agreement ("CLA").
✔

**Comment by amrit-1901** [comment]
@SamirMokiem Can you name the commit to something more descriptive?

**Comment by SamirMokiem** [comment]
> @SamirMokiem Can you name the commit to something more descriptive?

Done :)

**Comment by amrit-1901** [comment]
Thanks!

**Comment by aisha8834** [comment]
9b170fca-99ae-4e9c-9c72-2fee2083c427

**Comment by aisha8834** [comment]
How  do l wort as a sticker

**Pull request merged**
