### PR TITLE
Support for Animated Stickers

### PR DESCRIPTION
**Pull request by darshanip**
Support for 64 frames only.

### CODE REVIEW

**Comment by Dwite** [comment]
Hey, good to see the is work in direction for animated stickers 👍 Do you know if the size limit is the same for animated stickers as for regular one? 100 KB?

**Comment by darshanip** [comment]
@Dwite Nope, I don't have idea but why they no pushing official changes even after rolling out that feature in production too?

**Comment by Dwite** [comment]
@darshanip do you know how that changes should look like? I mean since there are patched WhatsApp that support animated stickers, they probably copied it from WhatsApp production that has support for animated stickers?

Or 64 frames was just a guess from you?

**Comment by darshanip** [comment]
@Dwite 64 frames was just a guess but even if you do 64k it'll not work :(

**Comment by UdeeshaInduwara** [comment]
@darshanip Is this solution work for you? I try this. but didn't work.

**Comment by darshanip** [comment]
> @darshanip Is this solution work for you? I try this. but didn't work.

Nope.

**Comment by UdeeshaInduwara** [comment]
ok thanks.

> > @darshanip Is this solution work for you? I try this. but didn't work.
> 
> Nope.

Ok. Thanks and any working solution for animated stickers ?

**Comment by Alex193a** [comment]
> Support for 64 frames only.

There will be no restrictions on the number of frames, or at least, WhatsApp **currently** does no checking on that.

> @darshanip Is this solution work for you? I try this. but didn't work.

> Nope.

WhatsApp does not support importing third party animated stickers at the moment. This feature, although already implemented, is not yet active for this reason this repository has not yet been updated.

>  Do you know if the size limit is the same for animated stickers as for regular one? 100 KB?

The size limit for animated stickers is 300 KB.

**Comment by diegulog** [comment]
Para los desarrolladores que estén preparando su aplicación para las pegatinas animadas, pueden comenzar hacerlo pero necesitan un teléfono rooteado. Indico los pasos con lo que he conseguido instalar pegatinas de terceros:

1.- Asegúrese de tener un explorador de archivos que admita la raíz. Si no tiene mucha idea sobre esto, descargue el * Solid Explorer File Manager * desde Play Store. Ahora, cuando abra la aplicación, concédele acceso de root.
Abra el Administrador de archivos y diríjase a la partición raíz.
Luego vaya a Datos > Datos  y navegue a la carpeta  com.whatsapp .
Vaya a la carpeta shared_prefs y busque el archivo com.whatsapp_preferences.xml

Ahora agregue las líneas siguientes a ese archivo xml, en cualquier lugar dentro de las etiquetas <map> 
<boolean name="third_party_animated_sticker" value="true" />
 </map> 
2.  En ContentProvider agregar:

    private val ANIMATED_STICKER = "animated_sticker_pack"
    private val STICKER_FILE_ANIMATED = "is_animated_sticker"

private fun getStickerPackInfo(uri: Uri, stickerPackList: List<StickerSet>): Cursor {
   val cursor = MatrixCursor(
            arrayOf(
                STICKER_PACK_IDENTIFIER_IN_QUERY,
                STICKER_PACK_NAME_IN_QUERY,
                STICKER_PACK_PUBLISHER_IN_QUERY,
                STICKER_PACK_ICON_IN_QUERY,
                ANDROID_APP_DOWNLOAD_LINK_IN_QUERY,
                PUBLISHER_EMAIL,
                PUBLISHER_WEBSITE,
                PRIVACY_POLICY_WEBSITE,
                LICENSE_AGREENMENT_WEBSITE,
                IMAGE_DATA_VERSION,
                AVOID_CACHE,
                ANIMATED_STICKER

            )
        )
      for (stickerPack in stickerPackList) {
            val builder = cursor.newRow()
            ......................
            ......................
            ......................
            builder.add(stickerPack.isAnimated)
        }
        cursor.setNotificationUri(Objects.requireNonNull(context).contentResolver, uri)
        return cursor
}

private fun getStickersForAStickerPack(uri: Uri): Cursor {
        val identifier = uri.lastPathSegment
        val cursor = MatrixCursor(arrayOf(STICKER_FILE_NAME_IN_QUERY, 
             STICKER_FILE_EMOJI_IN_QUERY, STICKER_FILE_ANIMATED))
        for (stickerSet in stickerPackList()) {
            if (identifier == stickerSet.id.toString()) {
                for (sticker in stickerSet.stickers) {
                    cursor.addRow(arrayOf<Any>(sticker.fileName, sticker.emoji, sticker.isAnimated))
                }
            }
        }
        cursor.setNotificationUri(Objects.requireNonNull(context).contentResolver, uri)
        return cursor
    }


Verificar que cada sticker animado no sea mayor a 300Kb

**Comment by aritradhabal** [comment]
> @darshanip Hey, good to see the is work in direction for animated stickers  Do you know if the size limit is the same for animated stickers as for regular one? 100 KB?

i have the same question also, the size is limited to 100kb :(

**Comment by simonzhexu** [comment]
Hi, @darshanip darshanip Thank you for your contribution to this open source repo. Appreciate you taking the time to write the code to provide animated sticker support. Now that we have put the support for animated sticker in (https://github.com/WhatsApp/stickers/wiki/Animated-Stickers), I wonder if you are ok with me closing this pull request.

**Pull request closed without merging**
