### PR TITLE
Update default application id exception message

### LINKED ISSUE #464: [Android] The applicationId isn't the line 16 anymore
https://github.com/WhatsApp/stickers/blob/86d38d3da0e1d1204269bb5c9078d6bc277f78cb/Android/app/build.gradle#L57
According to build.gradle, you have to change the applicationId in line 16. I don't know if at any point in time it was at that line, but seems that right now it's at line 10.
Line 10:
https://github.com/WhatsApp/stickers/blob/86d38d3da0e1d1204269bb5c9078d6bc277f78cb/Android/app/build.gradle#L10
Line 16:
https://github.com/WhatsApp/stickers/blob/86d38d3da0e1d1204269bb5c9078d6bc277f78cb/Android/app/build.gradle#L16

### PR DESCRIPTION
**Pull request by juandelacruz23**
Making changes to resolve the problem describe in issue #464

Closes #464

### CODE REVIEW

**Comment by Zandor300** [comment]
@juandelacruz23 In order for the WhatsApp team to merge this, you have to have filled in the CLA. If you have not done so already, make sure you do: https://github.com/WhatsApp/stickers/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla

**Comment by juandelacruz23** [comment]
@Zandor300 Done! :)

**Comment by simonzhexu** [comment]
Thank you!

**Comment by simonzhexu** [comment]
Great team work guys, @Zandor300 @MarvinJWendt Thank you!

**Pull request merged**
