### PR TITLE
Add issue template

### PR DESCRIPTION
**Pull request by Zandor300**
Contents of this file will be automatically filled in when creating a new issue in the repo. It contains instructions on how to improve the issue and has some headings added in.

### CODE REVIEW

**Comment by Zandor300** [comment]
@simonzhexu @amrit-1901

**Comment by simonzhexu** [comment]
Hi @Zandor300 . Really appreciate your help. Pull request looks good. Could you please complete the CLA mentioned in the https://github.com/WhatsApp/stickers/blob/master/CONTRIBUTING.md

**Comment by Zandor300** [comment]
@simonzhexu I filled in the CLA. I also added a new thing to the issue template. See https://github.com/WhatsApp/stickers/pull/234/commits/7961df8e0a611480bb6e2bea2879e4038ab2f9db

**Comment by Zandor300** [comment]
@simonzhexu @amrit-1901  
Can this still be merged? This would really help with people not providing enough information to help them.

**Pull request merged**
