### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by joshua-612**
added script to easily convert batch of png files to the correct 512x512 resolution keeping the original aspect ratio.
Another script to convert batch of png files to webp files.

### CODE REVIEW

**Comment by aihmgmal** [comment]
Did you update the mobile files

**Comment by aihmgmal** [comment]
Have you updated the animated stickers

**Comment by joshua-612** [comment]
> Have you updated the animated stickers

No the animated stickers are not yet supported for third party apps.
Maybe they will be when they come to stable whatsapp version

**Comment by MarvinJWendt** [comment]
Hi @joshua-612, thank you for making those scripts 👍 Unfortunately, we cannot recommend external and/or unofficial programs because WhatsApp has no control over them and cannot ensure that the linked programs will not harm users in the future.

See #431

**Pull request closed without merging**
