### PR TITLE
Migrate to Android Data Binding library

### PR DESCRIPTION
**Pull request by ar-arvind**
Migrated the app to Android Data Binding library which improves `app performance` and `eliminates boilerplate code`.

### CODE REVIEW

**Comment by simonzhexu** [comment]
Hi @ar-arvind , I thought hard about whether to merge this in. I think while this is a good change to make the app more readable, a majority of users of our code may not be very familiar with Android. Therefore, they might not be familiar with DataBinding, and this change makes it hard to understand the code. So I would rather leave this code base very basic. Therefore, I don't want to merge this into the code base. Does it make sense?

**Comment by ar-arvind** [comment]
Hi @simonzhexu, Yes you're correct, this make it little hard for users to understand the code. I will close the pull request. Thanks!

**Comment by simonzhexu** [comment]
Thanks @ar-arvind  for your contribution! I hope you are not discouraged by this. Please keep them coming.

**Comment by ar-arvind** [comment]
@simonzhexu 👍 Thanks for your support!

**Pull request closed without merging**
